### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 911TechGuy911** [Weatherlights/Winget-AutoUpdate-Intune#10]
### The problem

Imported the ADMX and ADML files as supplied, but the settings do not come up under configuration profiles under "Windows components".

### What version of WAU has the issue?

1.17.4

### What version of Windows are you using (ex. Windows 11 22H2)?

Windows 11 22H2 Enterprise

### What version of winget are you using?

v10.0.22621.1848

### Log information

```txt
N/A - Issue is on the Intune side with the ADMX /ADML files
```

### Additional information

Followed the instructions to the T
Not sure if I am missing something or if it's a bug in Intune or WUA

**Comment by 911TechGuy911** [comment]
Anyone else experiencing this issue?

**Comment by ITSourcePro** [comment]
This is related to this previous bug that went stale as well: https://github.com/Weatherlights/Winget-AutoUpdate-Intune/issues/7

Open the ADMX file and change the revision from "1.04.0000" to "1.04" the additional .0000 makes its fail on Import. Someone needs to update it on GitHub.

**Comment by 911TechGuy911** [comment]
> This is related to this previous bug that went stale as well: #7
> 
> Open the ADMX file and change the revision from "1.04.0000" to "1.04" the additional .0000 makes its fail on Import. Then reupload the new files to Intune. Someone needs to update it on GitHub.

Thanks! This worked for me.

**Comment by the-project-group** [comment]
Same for me.
I forked and created a PR - but for me it doesn't work.
`<policyDefinitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" revision="1.04" xsi:schemaLocation="" schemaVersion="1.0" xmlns="http://www.microsoft.com/GroupPolicy/PolicyDefinitions">
`
It's still missing in Intune:
![CleanShot 2023-09-15 at 14 26 31@2x](https://github.com/Weatherlights/Winget-AutoUpdate-Intune/assets/127997549/89807524-caea-435e-9cad-bf4cdb77022f)
![CleanShot 2023-09-15 at 14 26 59@2x](https://github.com/Weatherlights/Winget-AutoUpdate-Intune/assets/127997549/ead4c284-21d7-48e9-a70c-8703dfe25e51)

**Comment by Weatherlights** [comment]
I now integrated the fix into the ADMX. Thanks... somehow I have not received updates on the comments. Sorry for my late reaction on this.
