### ISSUE TITLE
[Feature Request]: Everygreen-ADMX to get your ADMX included

### ISSUE THREAD

**Issue by Karl-WE** [Weatherlights/Winget-AutoUpdate-Intune#12]
### The request

Support Downloads of Winget Autoupdate-Intune ADMX via EvergreenADMX.

There is this great project to keep ADMX updated.  Wanna hook up so it is supported by this solution?

**Comment by msfreaks** [comment]
Evergreen ADMX is meant to keep ADMX files in your on-premises Active Directory up-to-date. How would this benefit this project?

**Comment by Karl-WE** [comment]
@msfreaks I understand you concern it is aimed at ADMX files for on-premises AD DS, but also EvergreenADMX already spanning over a variety of ADMX templates not limited to Windows OS. Including these admx templates could be of use to manage GPO for this tool. 

I understand most might use the ADMX files to be imported in Intune, yet there are a hybrid join scenarios where the ADMX can be used for GPOs.

**Comment by Karl-WE** [comment]
as I understand the is no intention from this side or evergreen admx maintainer, PR closed. Thanks for your consideration.
