### ISSUE TITLE
[Bug]: Document references Winget-AutoUpdate-aaS and Winget-AutoUpdate-Configurator

### ISSUE THREAD

**Issue by MarcLaf** [Weatherlights/Winget-AutoUpdate-Intune#18]
### The problem

I am just looking for clarification on the correct name of the product. Is it Winget-AutoUpdate-aaS or Winget-AutoUpdate-Configurator as the install document references both. When adding the app to Intune via new store method, it says to search for Winget-AutoUpdate-aaS but that doesn't show up, Winget-AutoUpdate-Configurator shows up. This is also what is referenced in the manual LOB method.

### What version of WAU has the issue?

N/A

### What version of winget are you using?

N/A

**Comment by Weatherlights** [comment]
Hey

thank you for the hint. I changed the documentation and added a note to the former name of the tool.

Sorry for the mixup. The tool had the initial name Winget-AutoUpdate-Configurator and currently I am renaming it to Winget-AutoUpdate-aaS. The project is renamed to better outline what value this project adds to the original WAU.

The store release will also be renamed with the next update so this all is more consistent.

Best
Hauke
