### ISSUE TITLE
Descriptions for ADMX template

### ISSUE THREAD

**Issue by thomas-ingle** [Weatherlights/Winget-AutoUpdate-Intune#3]
Have configured the **Application List** policy to include only apps we want to update. I have also configured the **Use White List instead of Black List** policy to enabled and applications not in the list are being updated. Is something backwards here? Can't find an explanation.

**Comment by KnifMelti** [comment]
Hello!
I've implemented the list in a GPO function now in the original **WAU**  after @Weatherlights tipped me in https://github.com/Romanitho/Winget-AutoUpdate/discussions/256#discussioncomment-4710599
But to make it work I had to convert the list from registry to an array of strings (from an array of properties from registry) to make it work with the comparison `-contains` , maybe that's the case here?
I don't know how the list from GPO is pulled in **Winget-AutoUpdate-Intune**, but it feels like maybe that's the problem...
```
function Get-ExcludedApps {

    if ($GPOList) {
        
        $Key = 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Romanitho\Winget-AutoUpdate\BlackList\'
        $ValueNames = (Get-Item -Path "HKLM:\SOFTWARE\Policies\Romanitho\Winget-AutoUpdate\BlackList").Property
        
        foreach ($ValueName in $ValueNames) {
            $AppIDs = [Microsoft.Win32.Registry]::GetValue($Key, $ValueName, $false)
            [PSCustomObject]@{
                Value = $ValueName
                Data = $AppIDs
            }
        }

        return $AppIDs
        
    }
    elseif (Test-Path "$WorkingDir\excluded_apps.txt") {

        return (Get-Content -Path "$WorkingDir\excluded_apps.txt").Trim() | Where-Object { $_.length -gt 0 }

    }

}

function Get-IncludedApps {

    if ($GPOList) {

        $Key = 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Romanitho\Winget-AutoUpdate\WhiteList\'
        $ValueNames = (Get-Item -Path "HKLM:\SOFTWARE\Policies\Romanitho\Winget-AutoUpdate\WhiteList").Property
        
        foreach ($ValueName in $ValueNames) {
            $AppIDs = [Microsoft.Win32.Registry]::GetValue($Key, $ValueName, $false)
            [PSCustomObject]@{
                Value = $ValueName
                Data = $AppIDs
            }
        }

        return $AppIDs

    }
    elseif (Test-Path "$WorkingDir\included_apps.txt") {

        return (Get-Content -Path "$WorkingDir\included_apps.txt").Trim() | Where-Object { $_.length -gt 0 }

    }

}
```
In Winget-Upgrade.ps1 before the comparision:
```
        #Fix the array if GPO List!
        if ($GPOList) {
            $toUpdate = $toUpdate.Data
            $toSkip = $toSkip.Data
        }
```

**Comment by Weatherlights** [comment]
Hey @thomas-ingle 

I would need a little more input from you. Can you check wether the registry key HKEY_LOCAL_MACHINE\SOFTWARE\Policies\weatherlights.com\Winget-AutoUpdate\UseWhiteList is set to 1 or 0 (or does not exist at all) and the existence of the file
%PROGRAMDATA%\Winget-AutoUpdate-Configurator\included_apps.txt
and check if the LastCommand.txt includes the -UseWhiteList parameter

If the key exist and is set to 1 please also check the key
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Winget-AutoUpdate\WAU_UseWhiteList

I also fixed a behaviour where it was possible that the app was installed without having a policy in place... this had the effect that everything is updated (running WAU simply 'as is'). With the newest version this is fixed. So an explaination could be that the policy from intune was just not there yet before the tool has run.

**Comment by Weatherlights** [comment]
Hey @KnifMelti 

thanks for the input :). My mechanism is very simply: Before I configure WAU I convert the registry content in a corresponding txt file which is referenced upon the configuration of WAU. So I generate a list and then reference it.

I try to build around WAU rather not within WAU to keep the level complexity low on my end :).

**Comment by KnifMelti** [comment]
Nice! Mind if I reuse the `ForEach ( $item in $list.PSObject.Properties | where { $_.Name -match "[0-9]+" } ) { $parsedList += $item.Value + "``n" }` in **WAU**?

**Comment by KnifMelti** [comment]
...changed my mind, but thanks (I have a stable Function now - have just begun coding in PS)!

**Comment by Weatherlights** [comment]
I would not have guessed that :D. But yea in the no need to screw something up just for the looks :).
