### ISSUE TITLE
[Feature Request]: Update Winget-AutoUpdate-aaS App in MS Store - to include WAU 1.20.+

### ISSUE THREAD

**Issue by saqib-s** [Weatherlights/Winget-AutoUpdate-Intune#35]
### The request

Winget Auto Update has been update to: v1.20.1
https://github.com/Romanitho/Winget-AutoUpdate/releases/tag/v1.20.1

Can you update the Winget-AutoUpdate-aaS App in MS Store to include this new version of WAU.

**Comment by Weatherlights** [comment]
Will do and working on it.

**Comment by Weatherlights** [comment]
Updated to WAU 1.20.0... next release will also include WAU 1.20.1 (which is currently in testing).
