### ISSUE TITLE
[Bug]: Issue in _AppID-template.ps1

### ISSUE THREAD

**Issue by RHDHV-simon-sutcliffe** [Weatherlights/Winget-AutoUpdate-Intune#52]
### The problem

Incorrect value used in function

```
if ( $Configuration."InvokeModsApp" ) {
        ForEach ( $InvokeModsApp in $Configuration."RemoveModsReg" ) {
            $Run = $InvokeModsApp.Run;
            $RunSwitch = $InvokeModsApp.RunSwitch;
            $RunWait = $InvokeModsApp.RunWait;
            $User = $InvokeModsApp.User;
        
            Invoke-ModsApp $Run $RunSwitch $RunWait $User;
        }
    }
```
    
    I believe this should be $Configuration."InvokeModsApp"
    

### What version of WAU has the issue?

1.06.0034

### What version of Windows are you using (ex. Windows 11 22H2)?

Windows 11 24H2

### What version of winget are you using?

v1.9.25200

**Comment by RHDHV-simon-sutcliffe** [comment]
@Weatherlights Do you look at these and comment?

**Comment by Weatherlights** [comment]
Yes I do. I just didn't had the time this month to look to deep into anything yet. But you are totally right this is the wrong variable.

The new mods are not documented yet while of course you can find about them by looking into the code. But I fixed it now for the next release

**Comment by RHDHV-simon-sutcliffe** [comment]
Thanks for fixing this in the next build
