### ISSUE TITLE
[Bug]: Invalid value: '1.04.0000' for attribute revision. When opening in Group Policy Manager.

### ISSUE THREAD

**Issue by ITSourcePro** [Weatherlights/Winget-AutoUpdate-Intune#7]
### The problem

Revision needs to be 1.04 in the ADMX file, otherwise you get an error "Invalid value: '1.04.0000' for attribute revision. File: C:\WINDOWS\PolicyDefinitions\WinGet-AutoUpdate-Configurator.admx, line 1, column 244"

﻿<policyDefinitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" revision="1.04.0000" xsi:schemaLocation="" schemaVersion="1.0" xmlns="http://www.microsoft.com/GroupPolicy/PolicyDefinitions">
﻿
﻿
![Screenshot 2023-05-22 105131](https://github.com/Weatherlights/Winget-AutoUpdate-Intune/assets/71308090/c196f725-416a-4471-b569-e58c142c6b04)

### What version of WAU has the issue?

1.04.0010

### What version of Windows are you using (ex. Windows 11 22H2)?

Windows 11 22H2

### What version of winget are you using?

v1.5.1361-preview

### Log information

```txt
"Invalid value: '1.04.0000' for attribute revision. File: C:\WINDOWS\PolicyDefinitions\WinGet-AutoUpdate-Configurator.admx, line 1, column 244" in Group Policy Editor.
```

**Comment by ChrisMcGhan** [comment]
This ADMX has been pending for days. I finally added it to C:\Windows\PolicyDefinitions and opened Group Policy Editor on Windows 11 and can confirm the error message. I then uploader the ADMX to ChatGPT 4 and asked it about line 1: 

Me: Windows is reporting error:  Invalid value 1.04.0000 for attribute revision

ChatGPT: The revision attribute for the policyDefinitions tag in an ADMX file must be in the format "MAJOR.MINOR", where both MAJOR and MINOR are integer values. The format you've used (1.04.0000) doesn't fit this requirement.

You should revise the attribute value to fit the correct format. If your major revision is 1 and your minor revision is 4, then the correct value for the revision attribute would be "1.4".

Here's the corrected line:

<policyDefinitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" revision="1.4" xsi:schemaLocation="" schemaVersion="1.0" xmlns="http://www.microsoft.com/GroupPolicy/PolicyDefinitions">
